spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/${DATABASE}
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# 테스트용 mybatis 추가 설정
mybatis:
  configuration:
     map-underscore-to-camel-case: true
  mapper-locations: /mapper/**/*.xml